[package]
name = "hotkey-macros"
version = "0.2.0"
edition = "2024"

[dependencies]
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
features = [
    "full",
    "extra-traits",
]
version = "2.0"

[lib]
proc-macro = true
